COMPILER = gcc

# compile our stuff
all:
	@$(COMPILER) -o account.o account.c
	@$(COMPILER) -o linkedlist.o linkedlist.c
	@chmod 700 account.o
	@chmod 700 linkedlist.o

# remove unecessary files
clean:
	@rm -f account.o
	@rm -f linedlist.o
